Update readme to have a more complete compose file
31z4/storm-docker pull request #5
Opened 2016-10-31 15:55 UTC by edbo

I changed the docker-compose a bit so you can also see the ui and it includes a fix that allows for uploading to the cluster more easily.

2016-11-01 14:38 UTC, 31z4 requested changes

2016-11-01 14:38 UTC, 31z4 commented on README.md
> +            -c storm.zookeeper.servers="[\"zookeeper\"]"
This is done by default if no config provided. Please see https://github.com/31z4/storm-docker/blob/master/1.0.2/docker-entrypoint.sh#L15-L16

2016-11-01 14:38 UTC, 31z4 commented on README.md
> +            - zookeeper
I don't think the UI depends on Zookeeper.

2016-11-01 14:38 UTC, 31z4 commented on README.md
> +            - zookeeper
Linking with Zookeeper is unnecessary.

2016-11-01 14:40 UTC, 31z4 commented
@edbo could you please clarify on this

> it includes a fix that allows for uploading to the cluster more easily

What exactly do you mean?

2016-11-01 19:42 UTC, edbo commented
I wasn't able to update to the storm cluster without setting a ```storm.local.hostname```

2016-11-05 11:05 UTC, 31z4 commented
@edbo could you please create an issue for this describing all the details? Or do it right here.

2016-11-05 20:33 UTC, edbo commented on README.md
> +            -c storm.zookeeper.servers="[\"zookeeper\"]"
Nice didn't spot that.

2016-11-05 20:33 UTC, edbo commented
I get the error when using a command like tihs:

```
storm  jar target/file-1.0-SNAPSHOT-jar-with-dependencies.jar com.somecompany.TestTopology test
```

```
475  [main] INFO  o.a.s.StormSubmitter - Generated ZooKeeper secret payload for MD5-digest: -7118960670403454401:-7392511036754296696
536  [main] INFO  o.a.s.s.a.AuthUtils - Got AutoCreds []
611  [main] WARN  o.a.s.u.NimbusClient - Ignoring exception while trying to get leader nimbus info from localhost. will retry with a different seed host.
org.apache.storm.thrift.transport.TTransportException
	at org.apache.storm.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.transport.TTransport.readAll(TTransport.java:86) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.transport.TFramedTransport.read(TFramedTransport.java:101) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.transport.TTransport.readAll(TTransport.java:86) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.Nimbus$Client.recv_getClusterInfo(Nimbus.java:1156) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.Nimbus$Client.getClusterInfo(Nimbus.java:1144) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:67) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:371) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:311) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:157) [storm-core-1.0.2.jar:1.0.2]
	at com.bitgamelabs.LiveTransactionTopology.main(LiveTransactionTopology.java:29) [chain_lightening-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
Exception in thread "main" org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [localhost]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:90)
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:371)
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:311)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:157)
	at com.bitgamelabs.LiveTransactionTopology.main(LiveTransactionTopology.java:29)
```

Setting the hostname to nimbus gets it working. I'm about to tweak it a bit to see if I can drop the other bits.

2016-11-05 21:41 UTC, edbo commented
I realised after your message about the config settings you were setting that I was running your new docker compose file against your old docker image that didn't have those values set. Was confusing the hell out of me.

Anyway, I'm closing this now in favour of two simpler ones that separate the changes.

2016-11-05 21:41 UTC, closed without merging