Add ui to docker compose example
31z4/storm-docker pull request #6
Opened 2016-11-05 21:27 UTC by edbo

Minimal config to get ui working

2016-11-13 05:25 UTC, 31z4 requested changes
Please also add a note regarding the UI below the compose example.

2016-11-14 13:30 UTC, edbo commented
OK I've made a small update to the notes as well now.

2016-11-14 13:48 UTC, 31z4 commented on README.md
> +Note: the supervisor logs will not currently work correctly in the UI.
Actually neither of logs will work from the UI.

2016-11-14 13:51 UTC, edbo commented on README.md
> +Note: the supervisor logs will not currently work correctly in the UI.
OK I've made this more general instead.

2017-08-08 13:49 UTC, closed without merging